name 'php_nginx'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures php_nginx'
long_description 'Installs/Configures php_nginx'
version '0.1.0'

depends 'php'
depends 'php-fpm'
depends 'nginx'
